### ISSUE TITLE
Run with CLI

### ISSUE THREAD

**Issue by ghost** [avotoko/javascript-deobfuscator#1]
Would you mind providing an example on running this locally via a nodejs script?

**Comment by avotoko** [comment]
I do not intend to release a CLI version.

**Comment by ghost** [comment]
What does this mean in the readme?

“It is a program designed to run on a PC console, and functioning in a browser is only a byproduct, and execution speed is slow.”

**Comment by avotoko** [comment]
> What does this mean in the readme?

I'm not sure what the question is about, but it's not a very meaningful sentence, so don't worry about it. 
I'm not very good at English. More specific or technical questions are easier to answer.
