### ISSUE TITLE
[Fixed] error: 'import' and 'export' may appear only with 'sourceType: "module"' (21:0)

### ISSUE THREAD

**Issue by ghost** [avotoko/javascript-deobfuscator#2]
I'm trying to de-obfuscate an entire module so I'm working on each file, one by one. 

Getting this error when trying to de-obfuscate code with import and export statements. 

`error: 'import' and 'export' may appear only with 'sourceType: "module"' (21:0)`

Any ideas?

**Comment by avotoko** [comment]
Updated. Please check 'sourceType=module' option and run it.

**Comment by ghost** [comment]
That works you are AWESOME. Thank you so much.

Looks like that de-obfuscated most of everything except the imported names. They still show obfuscated, I could probably figure those out manually if I need to.

e.g.
`import a1O from 'node-fetch';`

Also there are some hex values that http://jsnice.org/ converts but your script doesn't. (To be fair, jsnice is the the only place I've used that does convert.)

e.g. 
`0x1`
converts to 
`1`

Thanks again and awesome work you've done.

**Comment by avotoko** [comment]
> `import a1O from 'node-fetch';`

It is basically impossible to derive the original name programmatically and automatically.

> `0x1`

I don't think hexadecimal numbers will significantly prevent understanding the behavior of the script.

Thank you for using my program.
