### ISSUE TITLE
こんにちは、助けてください

### ISSUE THREAD

**Issue by ghost** [avotoko/javascript-deobfuscator#4]
このスクリプトをご覧ください

https://rentry.co/f5hha/raw

**Comment by avotoko** [comment]
Updated. Try it.

**Comment by ghost** [comment]
Thank you for the update, it works perfectly :D also, sorry for the issues but i didn't know that you replied to my issues (i saw notifications from github on my email now.)

**Comment by ghost** [comment]
Hello, i tried to deobfuscate this script, but it says "Uncaught Error: aborted", and when i use "brute" option then it says "Uncaught ReferenceError: k is not defined".
https://rentry.co/uzgpg/raw
