### ISSUE TITLE
[Fixed] Cannot deobfuscate obfuscator.io with max settings

### ISSUE THREAD

**Issue by ghost** [avotoko/javascript-deobfuscator#5]
Hello again, I don't think you have seen my reply on the old issue (https://github.com/avotoko/javascript-deobfuscator/issues/4#issuecomment-1044449667) so I will write a new one. Your program cannot deobfuscate obfuscator.io with maximum settings, when I try to deobfuscate with default options, I get error "error: aborted" and when in console it says to use the "brute" option I get the error "error: T is not defined" and when I use the "exclude obfuscator-io" option then the code is unreadable. I would like you to improve and fix your program and if there is an option to send you a donation, write me where I can do it. Here's another obfuscated code for an example: https://rentry.co/ysh7y/raw

**Comment by avotoko** [comment]
Sorry. I did not see the closed issue.
Updated. Try it.
